### PR TITLE
Use VNC to connect to Windows instances

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR updates the network rules to reflect that we are switching to using VNC to connect to Windows instances for the interim.

## 💭 Motivation and context ##

Due to issues with our Windows configuration and business needs we cannot currently use RDP for remote desktop. Instead we will use VNC in the interim with the goal to move back to RDP in the future.

## 🧪 Testing ##

Automated tests pass. When deployed with an update guacamole image (from https://github.com/cisagov/guacamole-packer/pull/56) everything works as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Ensure that all PRs related to https://github.com/cisagov/guacscanner/pull/16 are merged
- [ ] A Windows AMI supporting the switch to VNC is available in both the Production and Staging environments

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Make sense, but can we add some comment(s) somewhere explaining who is using port 5900 vs. 5901 for VNC and why?

**Comment by mcdonnnj** [comment]
> Make sense, but can we add some comment(s) somewhere explaining who is using port 5900 vs. 5901 for VNC and why?

Ah, sorry. Those must've gotten lost when I was shuffling commits and changes around. I'll update with the comments I originally had.

**Review by jsf9k — APPROVED** [review]
Approved, but I agree with @dav3r that a comment regarding the odd VNC port for Windows is in order.

**Comment by mcdonnnj** [comment]
@dav3r @jsf9k I was able to test and verify that we can use the same port for all VNC connections with the change in VNC server software on Windows instance. I have re-requested review from both of you due to these changes.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
Looks great! 🥇

**Pull request merged**
