### PR TITLE
Bump up the instance type for Kali instances so they have more RAM

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request bumps up the instance type for Kali instances so they have more RAM.

## 💭 Motivation and Context

One of the fed leads asked for more RAM for the Kali instances.

## 🧪 Testing

This change is currently deployed to env7 in our production environment.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)
- [x] Parameter tweak

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
I don't know yet if this is a change we will want to adopt permanently, but I went ahead and added @dav3r as a reviewer just to keep him in the loop.

**Comment by dav3r** [comment]
> I don't know yet if this is a change we will want to adopt permanently, but I went ahead and added @dav3r as a reviewer just to keep him in the loop.

Do we know what they are doing that requires more RAM?  It would be good to document that here.

**Comment by jsf9k** [comment]
> > I don't know yet if this is a change we will want to adopt permanently, but I went ahead and added @dav3r as a reviewer just to keep him in the loop.
> 
> Do we know what they are doing that requires more RAM? It would be good to document that here.

They were guessing that Burp Suite was eating up all the RAM and that's why they saw a Kali instance lock up.  I'm not convinced they identified the root cause.  I think this was just a stab in the dark.

**Comment by dav3r** [comment]
> > > I don't know yet if this is a change we will want to adopt permanently, but I went ahead and added @dav3r as a reviewer just to keep him in the loop.
> > 
> > 
> > Do we know what they are doing that requires more RAM? It would be good to document that here.
> 
> They were guessing that Burp Suite was eating up all the RAM and that's why they saw a Kali instance lock up. I'm not convinced they identified the root cause. I think this was just a stab in the dark.

OK, thanks for the context.  I don't think we should roll out this larger instance type across the board until we are sure it is truly needed.

**Comment by jsf9k** [comment]
Fixes cisagov/cool-system#106.

**Review by dav3r — APPROVED** [review]
Give the people what they want! ⚡

**Review by hillaryj — APPROVED** [review]
🧑‍🤝‍🧑

**Review by mcdonnnj — APPROVED** [review]
image

**Pull request merged**
