### PR TITLE
Fetch postfix certificate at Gophish instance startup

### LINKED ISSUE #115: Fetch postfix TLS certificate at Gophish instance startup
# 💡 Summary #

Gophish instances (which contain a Dockerized postfix container) should fetch the TLS certificate for their specified domain from our S3 certificates bucket (if available) and place it in the appropriate location for postfix to use it.

## Motivation and context ##

This will allow postfix to run with a valid and appropriate certificate for the instance.  It is also one of the acceptance criteria specified in https://github.com/cisagov/cool-system/issues/90. 

## Implementation notes ##

This issue does NOT include figuring out how the certificate is created and put in our S3 bucket.  Initially, that will be a manual process that we want to automate in the future.

## Acceptance criteria ##

- [ ] When a Gophish instance is deployed, the `fullchain.pem` and `privkey.pem` files for the appropriate TLS certificate (i.e. the one that corresponds to the `email_sending_domain` Terraform variable) are deployed to `/var/pca/pca-gophish-composition/secrets/postfix/` before postfix starts up.
- [ ] A mail client (e.g. Thunderbird) is able to securely connect to postfix without encountering any security exceptions (assuming that the TLS certificate is valid and unexpired).
- [ ] If a certificate for the specified domain is NOT found in S3, a warning is logged and the [default certificate data (from `cisagov/postfix-docker`)](https://github.com/cisagov/postfix-docker/tree/develop/src/secrets) is untouched.

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR makes Gophish instances fetch the certificate files for their email-sending domain and copies them to the appropriate location where postfix will use them.

I also added a bit of error-handling to the existing [`install-certificates.py`](https://github.com/cisagov/cool-assessment-terraform/blob/develop/cloud-init/install-certificates.py) script (see https://github.com/cisagov/cool-assessment-terraform/commit/523bcf3f6fa7688df6154cd13f7371fa17a9d508).

## 💭 Motivation and context ##

One of the requirements from https://github.com/cisagov/cool-system/issues/90 is to ensure that the assessment mail server (postfix) is configured with proper TLS certificates, so this PR delivers that feature.

Resolves #115.

Note that https://github.com/cisagov/pca-gophish-composition-packer/pull/49 was a necessary precursor to this PR.

## 🧪 Testing ##

I first deployed a fresh Gophish instance using an `email_sending_domain` whose wildcard certificate **did not exist** in our certificates S3 bucket.  That allowed me to verify that the new error-handling code worked as expected, which it did.  The default certificate files were not changed and `/var/log/cloud-init-output.log` showed the following output:
```
Error fetching 'my-certificates-bucket/live/mysuperfakedomain.gov/fullchain.pem' from S3: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
Exiting script!
```

Next, I deployed a fresh Gophish instance (with a fresh EBS Docker volume) using an `email_sending_domain` whose wildcard certificate **did exist** in our certificates S3 bucket.

After the instance started up, I verified the following:
* [x] The PCA-Gophish composition (which includes postfix) started up cleanly (`sudo systemctl status pca-gophish-composition`)
* [x] The certificate files in the postfix secrets directory were updated with real certificate data from S3:
```
$ ls -ltr /var/pca/pca-gophish-composition/secrets/postfix
total 16
-rw-r--r-- 1 root root  413 Jun  1 14:50 users.txt
-rw-rw-r-- 1 root root 5607 Jun  1 19:33 fullchain.pem
-rw-rw-r-- 1 root root 1704 Jun  1 19:33 privkey.pem

$ openssl x509 -in /var/pca/pca-gophish-composition/secrets/postfix/fullchain.pem -text -noout | grep -B5 "Subject:"
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Validity
            Not Before: May 24 16:28:33 2021 GMT
            Not After : Aug 22 16:28:33 2021 GMT
        Subject: CN = *.mysuperduperfakedomain.gov
```

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Approved.

Note that if you had rebased your changes on top of `origin/develop` after I committed my PR (instead of merging them into your branch) then all those commits from my previous PR wouldn't be listed.  I think that's a cleaner way of handling cases like this.

**Comment by dav3r** [comment]
> Note that if you had rebased your changes on top of `origin/develop` after I committed my PR (instead of merging them into your branch) then all those commits from my previous PR wouldn't be listed. I think that's a cleaner way of handling cases like this.

Yeah, I forgot that I created this branch back before your PR was merged.  Is there a good way to clean this up now?

**Comment by jsf9k** [comment]
> > Note that if you had rebased your changes on top of `origin/develop` after I committed my PR (instead of merging them into your branch) then all those commits from my previous PR wouldn't be listed. I think that's a cleaner way of handling cases like this.
> 
> Yeah, I forgot that I created this branch back before your PR was merged. Is there a good way to clean this up now?

No simple way that I know of.

**Review by mcdonnnj — APPROVED** [review]
Strong work 💪💪💪Thanks for getting this implemented.

**Pull request merged**
